package com.shubham.iginsulation

import com.shubham.iginsulation.databinding.*

object IDAssign {

    fun assign(binding: FragmentBClassBinding) {
        40001.also { binding.one.id = it }
        40002.also { binding.onePointFive.id = it }
        40003.also { binding.two.id = it }
        40004.also { binding.three.id = it }
        40005.also { binding.four.id = it }
        40006.also { binding.five.id = it }
        40007.also { binding.six.id = it }
        40008.also { binding.eight.id = it }
        40009.also { binding.eightPacket.id = it }
        40010.also { binding.ten.id = it }
        40011.also { binding.tenPacket.id = it }
        40012.also { binding.twelve.id = it }
        40013.also { binding.twelvePacket.id = it }
        40014.also { binding.sixteen.id = it }
        40015.also { binding.sixteenPacket.id = it }

        50001.also { binding.buttonOne.id = it }
        50002.also { binding.buttonTwo.id = it }
        50003.also { binding.buttonThree.id = it }
        50004.also { binding.buttonFour.id = it }
        50005.also { binding.buttonFive.id = it }
        50006.also { binding.buttonSix.id = it }
    }

    fun assign(binding: FragmentFClassBinding) {
        40001.also { binding.one.id = it }
        40002.also { binding.onePointFive.id = it }
        40003.also { binding.two.id = it }
        40004.also { binding.three.id = it }
        40005.also { binding.four.id = it }
        40006.also { binding.five.id = it }
        40007.also { binding.six.id = it }
        40008.also { binding.eight.id = it }
        40009.also { binding.eightPacket.id = it }
        40010.also { binding.ten.id = it }
        40011.also { binding.tenPacket.id = it }
        40012.also { binding.twelve.id = it }
        40013.also { binding.twelvePacket.id = it }
        40014.also { binding.sixteen.id = it }
        40015.also { binding.sixteenPacket.id = it }

        50001.also { binding.buttonOne.id = it }
        50002.also { binding.buttonTwo.id = it }
        50003.also { binding.buttonThree.id = it }
        50004.also { binding.buttonFour.id = it }
        50005.also { binding.buttonFive.id = it }
        50006.also { binding.buttonSix.id = it }
    }

    fun assign(binding: FragmentHClassBinding) {
        40001.also { binding.one.id = it }
        40002.also { binding.onePointFive.id = it }
        40003.also { binding.two.id = it }
        40004.also { binding.three.id = it }
        40005.also { binding.four.id = it }
        40006.also { binding.five.id = it }
        40007.also { binding.six.id = it }
        40008.also { binding.eight.id = it }
        40009.also { binding.eightPacket.id = it }
        40010.also { binding.ten.id = it }
        40011.also { binding.tenPacket.id = it }
        40012.also { binding.twelve.id = it }
        40013.also { binding.twelvePacket.id = it }
        40014.also { binding.sixteen.id = it }
        40015.also { binding.sixteenPacket.id = it }

        50001.also { binding.buttonOneOne.id = it }
        50002.also { binding.buttonOnePointFiveOne.id = it }
        50003.also { binding.buttonTwoOne.id = it }
        50004.also { binding.buttonThreeOne.id = it }
        50005.also { binding.buttonFourOne.id = it }
        50006.also { binding.buttonFiveOne.id = it }
        50007.also { binding.buttonSixOne.id = it }
        50008.also { binding.buttonEightOne.id = it }
        50009.also { binding.buttonTenOne.id = it }
        50010.also { binding.buttonTwelveOne.id = it }
        50011.also { binding.buttonSixteenOne.id = it }

        60001.also { binding.buttonOneTwo.id = it }
        60002.also { binding.buttonOnePointFiveTwo.id = it }
        60003.also { binding.buttonTwoTwo.id = it }
        60004.also { binding.buttonThreeTwo.id = it }
        60005.also { binding.buttonFourTwo.id = it }
        60006.also { binding.buttonFiveTwo.id = it }
        60007.also { binding.buttonSixTwo.id = it }
        60008.also { binding.buttonEightTwo.id = it }
        60009.also { binding.buttonTenTwo.id = it }
        60010.also { binding.buttonTwelveTwo.id = it }
        60011.also { binding.buttonSixteenTwo.id = it }

        70001.also { binding.percentageOne.id = it }
        70002.also { binding.percentageOnePointFive.id = it }
        70003.also { binding.percentageTwo.id = it }
        70004.also { binding.percentageThree.id = it }
        70005.also { binding.percentageFour.id = it }
        70006.also { binding.percentageFive.id = it }
        70007.also { binding.percentageSix.id = it }
        70008.also { binding.percentageEight.id = it }
        70009.also { binding.percentageTen.id = it }
        70010.also { binding.percentageTwelve.id = it }
        70011.also { binding.percentageSixteen.id = it }
    }

    fun assign(binding: FragmentChinaBinding) {
        40001.also { binding.one.id = it }
        40002.also { binding.onePointFive.id = it }
        40003.also { binding.two.id = it }
        40004.also { binding.three.id = it }
        40005.also { binding.four.id = it }
        40006.also { binding.five.id = it }
        40007.also { binding.six.id = it }
        40008.also { binding.eight.id = it }
        40009.also { binding.eightPacket.id = it }
        40010.also { binding.ten.id = it }
        40011.also { binding.tenPacket.id = it }
        40012.also { binding.twelve.id = it }
        40013.also { binding.twelvePacket.id = it }
        40014.also { binding.sixteen.id = it }
        40015.also { binding.sixteenPacket.id = it }

        50001.also { binding.buttonOneOne.id = it }
        50002.also { binding.buttonOnePointFiveOne.id = it }
        50003.also { binding.buttonTwoOne.id = it }
        50004.also { binding.buttonThreeOne.id = it }
        50005.also { binding.buttonFourOne.id = it }
        50006.also { binding.buttonFiveOne.id = it }
        50007.also { binding.buttonSixOne.id = it }
        50008.also { binding.buttonEightOne.id = it }
        50009.also { binding.buttonTenOne.id = it }
        50010.also { binding.buttonTwelveOne.id = it }
        50011.also { binding.buttonSixteenOne.id = it }

        60001.also { binding.buttonOneTwo.id = it }
        60002.also { binding.buttonOnePointFiveTwo.id = it }
        60003.also { binding.buttonTwoTwo.id = it }
        60004.also { binding.buttonThreeTwo.id = it }
        60005.also { binding.buttonFourTwo.id = it }
        60006.also { binding.buttonFiveTwo.id = it }
        60007.also { binding.buttonSixTwo.id = it }
        60008.also { binding.buttonEightTwo.id = it }
        60009.also { binding.buttonTenTwo.id = it }
        60010.also { binding.buttonTwelveTwo.id = it }
        60011.also { binding.buttonSixteenTwo.id = it }

        70001.also { binding.percentageOne.id = it }
        70002.also { binding.percentageOnePointFive.id = it }
        70003.also { binding.percentageTwo.id = it }
        70004.also { binding.percentageThree.id = it }
        70005.also { binding.percentageFour.id = it }
        70006.also { binding.percentageFive.id = it }
        70007.also { binding.percentageSix.id = it }
        70008.also { binding.percentageEight.id = it }
        70009.also { binding.percentageTen.id = it }
        70010.also { binding.percentageTwelve.id = it }
        70011.also { binding.percentageSixteen.id = it }
    }
    fun assign(binding: FragmentHeatBinding) {
        50001.also { binding.pointSix.id = it }
        50002.also { binding.pointEight.id = it }
        50003.also { binding.one.id = it }
        50004.also { binding.onePointFive.id = it }
        50005.also { binding.two.id = it }
        50006.also { binding.twoPointFive.id = it }
        50007.also { binding.three.id = it }
        50008.also { binding.threePointFive.id = it }
        50009.also { binding.four.id = it }
        50010.also { binding.fourPointFive.id = it }
        50011.also { binding.five.id = it }
        50012.also { binding.fivePointFive.id = it }
        50013.also { binding.sixRound.id = it }
        50014.also { binding.sixFlat.id = it }
        50015.also { binding.seven.id = it }
        50016.also { binding.eight.id = it }
        50017.also { binding.nine.id = it }
        50018.also { binding.ten.id = it }
        50019.also { binding.eleven.id = it }
        50020.also { binding.twelve.id = it }
        50021.also { binding.thirteen.id = it }
        50022.also { binding.fourteen.id = it }
        50023.also { binding.fifteen.id = it }
        50024.also { binding.sixteen.id = it }
        50025.also { binding.seventeen.id = it }
        50026.also { binding.eighteen.id = it }
        50027.also { binding.twenty.id = it }
        50028.also { binding.twentyTwo.id = it }
        50029.also { binding.twentyFive.id = it }
        50030.also { binding.twentyEight.id = it }
        50031.also { binding.thirty.id = it }
        50032.also { binding.thirtyFive.id = it }
        50033.also { binding.forty.id = it }
        50034.also { binding.fortyFive.id = it }
        50035.also { binding.fifty.id = it }
        50036.also { binding.sixty.id = it }
        50037.also { binding.seventy.id = it }
        50038.also { binding.eighty.id = it }
        50039.also { binding.ninety.id = it }
        50040.also { binding.hundred.id = it }
        50041.also { binding.oneTwenty.id = it }
        50042.also { binding.oneFifty.id = it }
        50043.also { binding.oneEighty.id = it }
    }

    fun assign(binding: FragmentSaleNewBinding) {
        20001.also { binding.saleNewOneName.id = it }
        20002.also { binding.saleNewTwoName.id = it }
        20003.also { binding.saleNewThreeName.id = it }
        20004.also { binding.saleNewFourName.id = it }
        20005.also { binding.saleNewFiveName.id = it }
        20006.also { binding.saleNewSixName.id = it }
        20007.also { binding.saleNewSevenName.id = it }
        20008.also { binding.saleNewEightName.id = it }
        20009.also { binding.saleNewNineName.id = it }
        20010.also { binding.saleNewTenName.id = it }
        20011.also { binding.saleNewElevenName.id = it }
        20012.also { binding.saleNewTwelveName.id = it }
        20013.also { binding.saleNewThirteenName.id = it }
        20014.also { binding.saleNewFourteenName.id = it }
        20015.also { binding.saleNewFifteenName.id = it }
        20016.also { binding.saleNewSixteenName.id = it }
        20017.also { binding.saleNewSeventeenName.id = it }
        20018.also { binding.saleNewEighteenName.id = it }
        20019.also { binding.saleNewNineteenName.id = it }
        20020.also { binding.saleNewTwentyName.id = it }

        20101.also { binding.saleNewOneRate.id = it }
        20102.also { binding.saleNewTwoRate.id = it }
        20103.also { binding.saleNewThreeRate.id = it }
        20104.also { binding.saleNewFourRate.id = it }
        20105.also { binding.saleNewFiveRate.id = it }
        20106.also { binding.saleNewSixRate.id = it }
        20107.also { binding.saleNewSevenRate.id = it }
        20108.also { binding.saleNewEightRate.id = it }
        20109.also { binding.saleNewNineRate.id = it }
        20110.also { binding.saleNewTenRate.id = it }
        20111.also { binding.saleNewElevenRate.id = it }
        20112.also { binding.saleNewTwelveRate.id = it }
        20113.also { binding.saleNewThirteenRate.id = it }
        20114.also { binding.saleNewFourteenRate.id = it }
        20115.also { binding.saleNewFifteenRate.id = it }
        20116.also { binding.saleNewSixteenRate.id = it }
        20117.also { binding.saleNewSeventeenRate.id = it }
        20118.also { binding.saleNewEighteenRate.id = it }
        20119.also { binding.saleNewNineteenRate.id = it }
        20120.also { binding.saleNewTwentyRate.id = it }

        20201.also { binding.saleNewOnePercentage.id = it }
        20202.also { binding.saleNewTwoPercentage.id = it }
        20203.also { binding.saleNewThreePercentage.id = it }
        20204.also { binding.saleNewFourPercentage.id = it }
        20205.also { binding.saleNewFivePercentage.id = it }
        20206.also { binding.saleNewSixPercentage.id = it }
        20207.also { binding.saleNewSevenPercentage.id = it }
        20208.also { binding.saleNewEightPercentage.id = it }
        20209.also { binding.saleNewNinePercentage.id = it }
        20210.also { binding.saleNewTenPercentage.id = it }
        20211.also { binding.saleNewElevenPercentage.id = it }
        20212.also { binding.saleNewTwelvePercentage.id = it }
        20213.also { binding.saleNewThirteenPercentage.id = it }
        20214.also { binding.saleNewFourteenPercentage.id = it }
        20215.also { binding.saleNewFifteenPercentage.id = it }
        20216.also { binding.saleNewSixteenPercentage.id = it }
        20217.also { binding.saleNewSeventeenPercentage.id = it }
        20218.also { binding.saleNewEighteenPercentage.id = it }
        20219.also { binding.saleNewNineteenPercentage.id = it }
        20220.also { binding.saleNewTwentyPercentage.id = it }

        20301.also { binding.saleNewOneQuantity.id = it }
        20302.also { binding.saleNewTwoQuantity.id = it }
        20303.also { binding.saleNewThreeQuantity.id = it }
        20304.also { binding.saleNewFourQuantity.id = it }
        20305.also { binding.saleNewFiveQuantity.id = it }
        20306.also { binding.saleNewSixQuantity.id = it }
        20307.also { binding.saleNewSevenQuantity.id = it }
        20308.also { binding.saleNewEightQuantity.id = it }
        20309.also { binding.saleNewNineQuantity.id = it }
        20310.also { binding.saleNewTenQuantity.id = it }
        20311.also { binding.saleNewElevenQuantity.id = it }
        20312.also { binding.saleNewTwelveQuantity.id = it }
        20313.also { binding.saleNewThirteenQuantity.id = it }
        20314.also { binding.saleNewFourteenQuantity.id = it }
        20315.also { binding.saleNewFifteenQuantity.id = it }
        20316.also { binding.saleNewSixteenQuantity.id = it }
        20317.also { binding.saleNewSeventeenQuantity.id = it }
        20318.also { binding.saleNewEighteenQuantity.id = it }
        20319.also { binding.saleNewNineteenQuantity.id = it }
        20320.also { binding.saleNewTwentyQuantity.id = it }
    }

    fun assign(binding: FragmentSaleDetailBinding) {
        30001.also { binding.saleDetailsOneName.id = it }
        30002.also { binding.saleDetailsTwoName.id = it }
        30003.also { binding.saleDetailsThreeName.id = it }
        30004.also { binding.saleDetailsFourName.id = it }
        30005.also { binding.saleDetailsFiveName.id = it }
        30006.also { binding.saleDetailsSixName.id = it }
        30007.also { binding.saleDetailsSevenName.id = it }
        30008.also { binding.saleDetailsEightName.id = it }
        30009.also { binding.saleDetailsNineName.id = it }
        30010.also { binding.saleDetailsTenName.id = it }
        30011.also { binding.saleDetailsElevenName.id = it }
        30012.also { binding.saleDetailsTwelveName.id = it }
        30013.also { binding.saleDetailsThirteenName.id = it }
        30014.also { binding.saleDetailsFourteenName.id = it }
        30015.also { binding.saleDetailsFifteenName.id = it }
        30016.also { binding.saleDetailsSixteenName.id = it }
        30017.also { binding.saleDetailsSeventeenName.id = it }
        30018.also { binding.saleDetailsEighteenName.id = it }
        30019.also { binding.saleDetailsNineteenName.id = it }
        30020.also { binding.saleDetailsTwentyName.id = it }

        30101.also { binding.saleDetailsOneRate.id = it }
        30102.also { binding.saleDetailsTwoRate.id = it }
        30103.also { binding.saleDetailsThreeRate.id = it }
        30104.also { binding.saleDetailsFourRate.id = it }
        30105.also { binding.saleDetailsFiveRate.id = it }
        30106.also { binding.saleDetailsSixRate.id = it }
        30107.also { binding.saleDetailsSevenRate.id = it }
        30108.also { binding.saleDetailsEightRate.id = it }
        30109.also { binding.saleDetailsNineRate.id = it }
        30110.also { binding.saleDetailsTenRate.id = it }
        30111.also { binding.saleDetailsElevenRate.id = it }
        30112.also { binding.saleDetailsTwelveRate.id = it }
        30113.also { binding.saleDetailsThirteenRate.id = it }
        30114.also { binding.saleDetailsFourteenRate.id = it }
        30115.also { binding.saleDetailsFifteenRate.id = it }
        30116.also { binding.saleDetailsSixteenRate.id = it }
        30117.also { binding.saleDetailsSeventeenRate.id = it }
        30118.also { binding.saleDetailsEighteenRate.id = it }
        30119.also { binding.saleDetailsNineteenRate.id = it }
        30120.also { binding.saleDetailsTwentyRate.id = it }

        30201.also { binding.saleDetailsOneQuantity.id = it }
        30202.also { binding.saleDetailsTwoQuantity.id = it }
        30203.also { binding.saleDetailsThreeQuantity.id = it }
        30204.also { binding.saleDetailsFourQuantity.id = it }
        30205.also { binding.saleDetailsFiveQuantity.id = it }
        30206.also { binding.saleDetailsSixQuantity.id = it }
        30207.also { binding.saleDetailsSevenQuantity.id = it }
        30208.also { binding.saleDetailsEightQuantity.id = it }
        30209.also { binding.saleDetailsNineQuantity.id = it }
        30210.also { binding.saleDetailsTenQuantity.id = it }
        30211.also { binding.saleDetailsElevenQuantity.id = it }
        30212.also { binding.saleDetailsTwelveQuantity.id = it }
        30213.also { binding.saleDetailsThirteenQuantity.id = it }
        30214.also { binding.saleDetailsFourteenQuantity.id = it }
        30215.also { binding.saleDetailsFifteenQuantity.id = it }
        30216.also { binding.saleDetailsSixteenQuantity.id = it }
        30217.also { binding.saleDetailsSeventeenQuantity.id = it }
        30218.also { binding.saleDetailsEighteenQuantity.id = it }
        30219.also { binding.saleDetailsNineteenQuantity.id = it }
        30230.also { binding.saleDetailsTwentyQuantity.id = it }

        30301.also { binding.saleDetailsOne.id = it }
        30302.also { binding.saleDetailsTwo.id = it }
        30303.also { binding.saleDetailsThree.id = it }
        30304.also { binding.saleDetailsFour.id = it }
        30305.also { binding.saleDetailsFive.id = it }
        30306.also { binding.saleDetailsSix.id = it }
        30307.also { binding.saleDetailsSeven.id = it }
        30308.also { binding.saleDetailsEight.id = it }
        30309.also { binding.saleDetailsNine.id = it }
        30310.also { binding.saleDetailsTen.id = it }
        30311.also { binding.saleDetailsEleven.id = it }
        30312.also { binding.saleDetailsTwelve.id = it }
        30313.also { binding.saleDetailsThirteen.id = it }
        30314.also { binding.saleDetailsFourteen.id = it }
        30315.also { binding.saleDetailsFifteen.id = it }
        30316.also { binding.saleDetailsSixteen.id = it }
        30317.also { binding.saleDetailsSeventeen.id = it }
        30318.also { binding.saleDetailsEighteen.id = it }
        30319.also { binding.saleDetailsNineteen.id = it }
        30320.also { binding.saleDetailsTwenty.id = it }

        30401.also { binding.saleDetailsOneTotal.id = it }
        30402.also { binding.saleDetailsTwoTotal.id = it }
        30403.also { binding.saleDetailsThreeTotal.id = it }
        30404.also { binding.saleDetailsFourTotal.id = it }
        30405.also { binding.saleDetailsFiveTotal.id = it }
        30406.also { binding.saleDetailsSixTotal.id = it }
        30407.also { binding.saleDetailsSevenTotal.id = it }
        30408.also { binding.saleDetailsEightTotal.id = it }
        30409.also { binding.saleDetailsNineTotal.id = it }
        30410.also { binding.saleDetailsTenTotal.id = it }
        30411.also { binding.saleDetailsElevenTotal.id = it }
        30412.also { binding.saleDetailsTwelveTotal.id = it }
        30413.also { binding.saleDetailsThirteenTotal.id = it }
        30414.also { binding.saleDetailsFourteenTotal.id = it }
        30415.also { binding.saleDetailsFifteenTotal.id = it }
        30416.also { binding.saleDetailsSixteenTotal.id = it }
        30417.also { binding.saleDetailsSeventeenTotal.id = it }
        30418.also { binding.saleDetailsEighteenTotal.id = it }
        30419.also { binding.saleDetailsNineteenTotal.id = it }
        30430.also { binding.saleDetailsTwentyTotal.id = it }
    }

    fun assign(binding: FragmentVarnishBinding) {
        20001.also { binding.mak200.id = it }
        20002.also { binding.mak500.id = it }
        20003.also { binding.mak1.id = it}
        20004.also { binding.mak5.id = it}
        20005.also { binding.mak20.id = it}
        20006.also { binding.pio200.id = it }
        20007.also { binding.pio500.id = it }
        20008.also { binding.pio1.id = it}
        20009.also { binding.pio5.id = it}
        20010.also { binding.pio20.id = it}
        20011.also { binding.ray200.id = it }
        20012.also { binding.ray500.id = it }
        20013.also { binding.ray1.id = it}
        20014.also { binding.ray5.id = it}
        20015.also { binding.ray20.id = it}
        20016.also { binding.bake200.id = it }
        20017.also { binding.bake500.id = it }
        20018.also { binding.bake1.id = it}
        20019.also { binding.bake5.id = it}
        20020.also { binding.bake20.id = it}
        20021.also { binding.super200.id = it }
        20022.also { binding.super500.id = it }
        20023.also { binding.super1.id = it}
        20024.also { binding.super5.id = it}
        20025.also { binding.super20.id = it}
        20026.also { binding.dia200.id = it }
        20027.also { binding.dia500.id = it }
        20028.also { binding.dia1.id = it}
        20029.also { binding.dia5.id = it}
        20030.also { binding.dia20.id = it}
        20031.also { binding.wil200.id = it }
        20032.also { binding.wil500.id = it }
        20033.also { binding.wil1.id = it}
        20034.also { binding.wil5.id = it}
        20035.also { binding.wil20.id = it}
        20036.also { binding.insu200.id = it }
        20037.also { binding.insu500.id = it }
        20038.also { binding.insu1.id = it}
        20039.also { binding.insu5.id = it}
        20040.also { binding.insu20.id = it}
        20041.also { binding.a1200.id = it }
        20042.also { binding.a1500.id = it }
        20043.also { binding.a11.id = it}
        20044.also { binding.a15.id = it}
        20045.also { binding.a120.id = it}
        20046.also { binding.a1w200.id = it }
        20047.also { binding.a1w500.id = it }
        20048.also { binding.a1w1.id = it}
        20049.also { binding.a1w5.id = it}
        20050.also { binding.a1w20.id = it}
        20051.also { binding.beck200.id = it }
        20052.also { binding.beck500.id = it }
        20053.also { binding.beck1.id = it}
        20054.also { binding.beck5.id = it}
        20055.also { binding.beck20.id = it}
        20056.also { binding.jyoti200.id = it }
        20057.also { binding.jyoti500.id = it }
        20058.also { binding.jyoti1.id = it}
        20059.also { binding.jyoti5.id = it}
        20060.also { binding.jyoti20.id = it}
    }
}